#!/usr/bin/env sh

# Use neovim when possible
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Stop making me type sudo >:|
for x in docker timeshift mount umount pacman updatedb poweroff shutdown reboot; do
    alias $x="sudo $x"
done

# Adds verbosity and shorten common commands
alias \
    bup="sudo timeshift --create" \
    res="sudo timeshift --restore" \
    upg="paru -Syu --noconfirm && doom -y upgrade && doom doctor" \
    upgp="docker stop portainer && docker rm portainer && docker pull portainer/portaine-ce:latest && docker run -d -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /docker/appdata/portainer:/data portainer/portainer-ce:latest" \
    upgd="doom upgrade && doom doctor" \
    batt="cat /sys/class/power_supply/BAT?/capacity" \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -v" \
    mkd="mkdir -pv" \
    rmd="rmdir -v" \
    ka="killall" \
    g="git" \
    conf="g --git-dir=$HOME/.dotfiles --work-tree=$HOME" \
    p="paru" \
    f="$FILE" \
    e="$EDITOR" \
    sv="sudo dinitctl" \
    svs="sudo dinitctl list" \
    usv="dinitctl" \
    usvs="sudo dinitctl list" \
    z="zathura --fork"

# Add color to commands
LS_COLORS='di=1;35:fi=0:ln=31:pi=5:so=5:bd=5:cd=5:or=31:mi=0:ex=35:*.rpm=90:*.png=35:*.gif=36:*.jpg=35:*.c=92:*.jar=33:*.py=93:*.h=90:*.txt=94:*.doc=104:*.docx=104:*.odt=104:*.csv=102:*.xlsx=102:*.xlsm=102:*.rb=31:*.cpp=92:*.sh=92:*.html=96:*.zip=4;33:*.tar.gz=4;33:*.mp4=105:*.mp3=106'
export LS_COLORS

alias \
    ls="ls -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi"
