#!/usr/bin/env sh

if test -n "$BASH_VERSION"; then
    [ -f "../bash/bash_profile" ] && . "../bash/bash_profile"
elif test -n "$ZSH_VERSION"; then
    [ -f "../zsh/zprofile" ] && . "../zsh/zprofile"
fi

# Explicit XDG_DIRS
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DATA_DIRS="/usr/local/share/:/usr/share/"
export XDG_CONFIG_DIRS="/etc/xdg"
export XDG_CACHE_HOME="$HOME/.cache"
#XDG_RUNTIME_DIR is set by pam

# Make XMonad XDG compliant
export XMONAD_CONFIG_DIR="$XDG_CONFIG_HOME/xmonad"
export XMONAD_DATA_DIR="$XDG_DATA_HOME/xmonad"
export XMONAD_CACHE_DIR="$XDG_CACHE_HOME/xmonad"

# Make bash-completion XDG compliant
export BASH_COMPLETION_USER_FILE="$XDG_CONFIG_HOME/bash-completion/bash_completion"

# Make package managers XDG compliant
export CABAL_CONFIG="$XDG_CONFIG_HOME/cabal"
export CABAL_DIR="$XDG_CACHE_HOME/cabal"
export STACK_ROOT="$XDG_DATA_HOME/stack"

export CARGO_HOME="$XDG_DATA_HOME/cargo"

export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export NVM_DIR="$XDG_DATA_HOME/nvm"

# Make Xauthority XDG compliant
# LightDM won't stand for this.
#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"

# PATH
export PATH="${PATH}:$HOME/.local/bin/:$HOME/.config/emacs/bin/:$HOME/.local/.stack/"
