#!/usr/bin/env sh

# Sets bindings for vi command mode.
bind -m vi-command \
	'Control-l: clear-screen' \
	'Control-a: beginning-of-line' \
	'Control-e: end-of-line'

# Sets bindings for vi insert mode.
bind -m vi-insert \
	'Control-l: clear-screen' \
	'Control-a: beginning-of-line' \
	'Control-e: end-of-line'
