# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  protonup-ng = {
    pname = "protonup-ng";
    version = "0.2.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/protonup-ng/protonup-ng-0.2.1.tar.gz";
      sha256 = "sha256-rys9Noa3+w4phttfcI1OGEDfHMy8s80bm8kM8TzssQA=";
    };
  };
}
