# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  ipfs-desktop = {
    pname = "ipfs-desktop";
    version = "v0.24.1";
    src = fetchFromGitHub {
      owner = "ipfs";
      repo = "ipfs-desktop";
      rev = "v0.24.1";
      fetchSubmodules = false;
      sha256 = "sha256-UWZK0LQnS+iZ00pPy2kAoaGTnsDLIL9sYCJ752s6JBg=";
    };
  };
}
